server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
jasypt:
  encryptor:
    password: EWRREWRERWECCCXC
spring:
  datasource:
    master:  # 数据源的名字:master
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ENC(qQMfixDCHvMIdlOtFCGwi61arSQJsKnNDoNB1+dgHOho6DLnupxqQFQojj2Jds+uOB+yYJC8N2GhmviYzTB35a7OWTuxrBsQo7/sKo3pC4M/AkaDMd6C0GHrEYhN6PWPrmfWXM8FHN9IW9WR70MIdCO1retq2qD4Z9ClkoTk4Og=)
      username: ENC(fTfrL4ai12GfD5BQNO5+Dw==)
      password: ENC(J6T1Y/cvXBAXfdomse3dUQ==)
      type: com.alibaba.druid.pool.DruidDataSource
    slave:   # 数据源的名字:slave_local
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/unicom_dict?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: MYSQL
    show-sql: true
    #hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialetc: org.hibernate.dialect.MySQL5Dialect
        driver-class-name: com.mysql.Driver
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  aop:
    auto: true